= Code Wars - How the Database Affects Your Java Application

== Abstract
With the ever-increasing importance for data and the ability to quickly capture and access it, it is essential to choose the proper method.
Developers write applications to store and retrieve the data underneath, but may not know the impact the lower layer has on their code or their work.
Maybe the data layer isn't something that keeps developers up at night, but maybe it should.
We know that different business needs or standards drive towards one technology or another, but how can we truly know which is the best technology for the job?
Do we understand why the existing practice became standard, or can we improve our lives with a better way?
In this session, we will learn how different data sources and a variety of query languages impact the amount of Java code required to store and retrieve data.
We will compare and contrast databases connecting to a main Java application to understand how each makes life easy or hard for us as developers.
From relational to NoSQL to graph, we will explore various types of data - the way it is stored underneath and how to go about retrieving it.
Learn which query languages fit the data store and how that also impacts the developer skillsets and code complexity.
A live-coding demo will bring all this to life, as the presenter shows exactly how the layer underneath changes how you write applications.
Come to this session and find out whether the solution actually fits the need, and if it doesn't, provide valuable criteria and reasoning for a change!

== Speaker Bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver.
She holds a Master’s degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value.
She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis!
Her passion is finding ways to organize chaos and deliver software more effectively.