= What you need to know: Data, apps, and AI for graph databases

== Alternate titles
* ??

== Tags
* graph
* database
* applications
* AI

== Short abstract
Graphs are different from other types of databases because they store relationships between data points like a network. This session will introduce the basics of graph databases, how to build applications with graphs, and their strengths in AI applications.

== Abstract
Graphs are different from other types of databases because they store relationships between data points. This makes them ideal for applications where the connections between data provides additional context, improving decision-making with existing data.

In this session, we will walk through what a graph database is and how it can transform your applications and data. We will explore creating, querying, and displaying data and learn how to integrate a graph database into applications. Finally, we will discuss how graph databases can be used in AI applications and the strengths they bring to the table. Live code will demonstrate these concepts in action.

Join us to learn how to leverage graph databases in your applications and AI projects.

== Alternate Abstract
In this connected world, traditional data stores often make it difficult to find valuable relationships. By making them a key component of the model, contextualizing a set of data becomes incredibly simple.

In this session, we will walk through what a graph database is and how it can transform your applications and data. We will explore creating, querying, and displaying data with tools to interact with the database. Then, we will look at how graphs are lending their strengths to the AI industry through vectors and GraphRAG. Live demos will show developers how to interact with graph data and use it in technical systems.

Join us to learn how graph databases are used to improve the data world and help developers easily extract/import connected data!

== Notes to committee/motivation
Technology moves so quickly that it can be hard to keep up. This session aims to be an introduction to key concepts for graph databases - how they work, their strengths, and how to use them. This session is a good fit for those who are new to graph or want to know how to get started using them in both traditional and AI applications.