= Fingerboard to Keyboard: Transposing One Profession to Another

== Alternate titles
* Composing Your Career: Tips for Navigating a Career Change

== Tags
* career
* learning
* developer
* musician
* programming

== Elevator pitch (300 words or less)
Whether changing careers or technologies, many others have taken leaps from seemingly unrelated paths. This session will share the presenter's story with some tips she's learned along the way and help you jumpstart your next adventure!

== Short abstract
Whether you are considering a career change or a new project, many others have taken leaps from seemingly unrelated paths. This session will share the presenter's journey from an arts to a sciences career and how to navigate challenges in a big change.

We will see how to apply already-learned skills to any path and gather a few tips to make the transition easier. Join this session to learn how to jumpstart your next adventure!

== Abstract
Whether you are considering a career change or a new project, many others have taken leaps from seemingly unrelated paths. This session will share the presenter's journey from an arts to a sciences career and how to navigate challenges in a big change.

We will see how to apply already-learned skills to any new path and gather a few of the presenter's tips for making it easier. Join this session to assemble some tools for pursuing your goals and jumpstart your next adventure!

== Notes to committee/motivation
I know several who have changed careers or pursued other things, but people always seem surprised. I want to share my experience so that others can see their next adventure is reachable.