= Pass or Play: What does GenAI mean for the Java developer?

== Alternate titles
* GenAI for the Java Developer: What You Need to Know

== Tags
* genai
* llm
* java
* developers

== Elevator pitch (300 characters or less)
You've been tasked with implementing or learning AI, but there's so much to know and not enough time. In this session, we will explore GenAI technologies and architectures, see how Java developers can utilize them, and focus on their real value. Come see how to play in the GenAI era.

== Short abstract
You've been tasked with implementing or learning AI, but there's so much to know and not enough time. 

In this session, we'll explore how these technologies operate and look at some of the common application architectures. Live-code examples will show how Java developers can utilize GenAI and help you determine where they can be best applied. Come see how to play in the GenAI era.

== Abstract
You've been tasked with implementing or learning AI, whether that includes LLMs, RAG, or MLOps. The sea of acronyms in this era of AI can feel like (and sometimes actually are) a black box for the complex logic and processes that underpin them. There's so much to learn and not enough time.

In this session, we'll explore how these technologies operate and the different practical ways GenAI is being used. We will explain common architectures for applications with GenAI, including RAG and GraphRAG. Live-code examples will show how Java developers can start using GenAI and help determine where they can be best applied. Come see how to play in the GenAI era.

== Notes to committee/motivation
It's hard for developers to understand the tangible benefits and drawbacks, as well as what it means for existing and future projects and business. This session aims to help developers sift through the weeds and better grasp what applies to them and how to get started.