= Get to Know the Real World

== Alternate Titles
* Get to Know the Real World: Discovering Connected Data with a Graph Database
* Get to Know the Real World with a Graph Database

== Abstract
In this connected world, traditional data stores often make it difficult to find valuable relationships.
By making them a key component of the model, contextualizing a set of data becomes incredibly simple.

In this session, we will walk through what a graph database is and how it can transform your applications and data.
We will explore creating, querying, and displaying data and learn how to use simple tools to interact with the database.
We will cover the whiteboard-friendly model and the basics of the Cypher query language.
Live demos will show developers how to interface with the database and the data in it.

Join us to learn how graph databases are used to improve the data world and help developers easily extract/import connected data!

== Speaker Bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver.
She holds a Master's degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value.
She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis!
Her passion is finding ways to organize chaos and deliver software more effectively.
