= Cliff Notes: What Java Developers Need to Know About Graph Databases

== Alternate titles
* How Do You Know If a Graph Database Solves the Problem?
* Cliff Notes: Why Graphs for Java Developers?
* Graphs: Why Java Developers Should Add Another Database

== Tags
* graph
* database
* data
* analysis

== Elevator pitch (300 characters or less)
Keeping up with database trends? Or learning graphs for a project? Or something else? In this session, we will see why a Java developer should bother adding another database. We'll hit the high points and get Java developers what they need to get started quickly and successfully with graph databases!

== Short abstract
Many developers are familiar with polyglot environments - matching databases to projects that play to their strengths. Whether you are a developer who likes learning the latest technologies, is required to learn for a project, or just curious about the graph segment, this session will show why Java developers should add a graph database to their toolbelts and where to use them. From data model to queries to applications, we will see how to utilize graphs alongside your current stack. Come to this session to hit the high points and started quickly and successfully with graph databases!

== Abstract
Many developers are familiar with polyglot environments and assigning database technologies to projects that play to their strengths. But what do we do when our existing data stores don't fit the need? Or we feel that we are missing insights in our data? Enter graphs.

Graphs form another type of data store and are ideal for highly-connected data sets. Whether you are a developer who likes learning the latest technologies, is required to learn for a project, or just curious about the graph segment, this session will show why Java developers should add a graph database to their toolbelts. We will discuss how these databases differ from others, what use cases are (and aren't!) good fits for a graph, and how organizing data in a graph can unlock deeper insights from the data you already have.

From data model to queries to applications, we will see how to utilize graphs alongside your current stack. Come to this session to hit the high points and started quickly and successfully with graph databases!

== Notes to committee/motivation
Graph databases are still relatively unknown to many organizations and developers. While the examples will focus on the graph database Neo4j, the concepts and skills can be used across many graph databases. My goal is to help relate unfamiliar technologies with skills they already have to give Java developers another option in their toolbelt for tackling everyday developer and business problems.
