= Organize your life with a personal knowledge graph

== Alternate titles

== Formats
* can present as solo speaker or co-present with https://github.com/jalakoo[Jason Koo^]

== Tags
* neo4j
* knowledge graph
* java
* python

== Elevator pitch (300 characters or less)
Can't remember the name of that genius developer you met last year, but remember pieces of your conversation? If only you could rank all your contacts by a few keywords. With a personal knowledge graph, you can!

In this talk, the presenters will show you how to build your own personal knowledge graph using Neo4j and help you discover new insights in your own data!

== Short abstract
Can't remember the name of that genius developer you met last year, but you remember pieces of your conversation? If only you could rank all your contacts by a few keywords. With a personal knowledge graph, you can!

In this talk, the presenters will show you how to build your own personal knowledge graph using Neo4j, a graph database. We'll walk through the process of importing information from a second brain platform and traverse the data using the Cypher query language. Learn how to build your own knowledge graph and discover new insights in your own data!


== Abstract
Can't remember the name of that genius developer you met last year, but you remember bits & pieces of your conversation? If only you could page rank all your contacts by a few memorable keywords. With a personal knowledge graph, you can!

In this talk, the presenters will show you how to build your own personal knowledge graph using Neo4j, a graph database. We'll walk through the process of importing information from a second brain platform (such as Evernote or Obsidian) into graph nodes and relationships. From there, we'll explore and traverse the data using the Cypher query language.

Come learn how to build your own knowledge graph and discover new insights in your own data!

== Notes to committee/motivation