= Import Dread: Why Is Data Ingestion So Hard?

== Alternate Titles
* Does Data Import Have to Suck Your Life Away?

== Abstract
In today's broad and fast-paced tech industry, there are many standards and recommended practices for IT systems and processes, but there is one capability that isn't yet universal - data import.
Moving and translating data isn't just a one-and-done task either.
It's a continuous cycle of updates to core and subsystem stores, feeding data gathered or crunched in various places to and from source-of-truth systems.

Whether dealing with new data, migrating data, or translating/integrating data, we must write code to move this valuable and temperamental asset across systems and structures for analysis.
These processes can consume a surprising amount of planning, time, and frustration.
Plus, they must handle incremental updates, changing business requirements, and system upgrades.
Can we reduce these headaches and find better tools to streamline and simplify these continuous processes?

In this session, we will find and test ways to transport and transform different types of data into of 3 main categories of databases (relational, nosql, and graph).
From extra tools and helpful hints to out-of-the-box solutions, come and learn how to reduce your project's critical path and focus more on business needs by simplifying the data import process!

== Notes to committee/motivation
It seems that no matter the database, the longest pole in the tent is getting the data transported from one system or format to another. I wanted to explore the various ways/tools and show how each provides positive and negative experiences for different scenarios.

== Speaker Bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver.
She holds a Master’s degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value.
She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis!
Her passion is finding ways to organize chaos and deliver software more effectively.