= Intro to Neo4j for Developers

== Alternate titles
* Graph Databases: Data Storage with Context
* Graph Databases - Solving Business Problems with Connected Data

== Tags
* intro
* use cases
* Cypher
* learning
* property graph

== Elevator Pitch (300 characters or less)
Traditional data stores often make it difficult to find valuable relationships. This is where graph can help. In this session, we will walk through what a graph database is and how it can transform your data. We will explore creating, querying, displaying, and interacting with your graph data.

== Abstract
In this connected world, traditional data stores often make it difficult to find valuable relationships. By making them a key component of the model, contextualizing a set of data becomes incredibly simple.

In this session, we will walk through what a graph database is and how it can transform your applications and data. We will explore creating, querying, and displaying data and learn how to use simple tools to interact with the database. We will cover the whiteboard-friendly model and the basics of the Cypher query language. Live demos will show developers how to interface with the database and the data in it.

Join us to learn how graph databases are used to improve the data world and help developers easily extract/import connected data!

== Alternate Abstract
In this connected world, traditional data stores often make it difficult to find valuable relationships. Graph databases focus not only on the entities, but the connections between them. By making relationships a key component of the model, contextualizing a set of data becomes incredibly simple. 
In this session, we will explore graphs and how they provide context in the way they store data. We will see how to transform our own projects into graph structures, optimize the model for querying, and access the data for maximum benefit through queries, visualization, and applications.
Join us to learn how graph databases are used to improve the data world and help developers easily make sense of connected data!

== Notes to committee/motivation
Many developers are not yet familiar with graph technologies and how they are useful. This session will explore the best cases to use graph and what it can do for business and technical needs.

Aims to provide context and some details for graph databases in general. While examples are based around Neo4j (company/product), we will focus on concepts that are applicable across many graph vendors and not limit discussion to Neo4j.

== Speaker Bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver.
She holds a Master’s degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value.
She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis!
Her passion is finding ways to organize chaos and deliver software more effectively.
