= Commonly Uncommon: Diverse Paths that Lead to Winning Outcomes

== Alternate titles
* Diverse Paths, Unified Success: How Varied Experiences Fuel Tech Innovation

== Tags
* career
* keynote
* tech
* innovation

== Abstract
We each have a unique combination of experiences that we bring to our career in tech. Many of us don't have an undergraduate, graduate, and/or doctorate in computer science. In this session, we will get a glimpse into the speaker's winding journey to a tech career and discuss how conventional and unconventional paths foster unique perspectives that create ideal conditions for inventive solutions and ideas. Find out how to leverage your diverse experiences in your career, encourage and welcome new additions, and contribute to the innovation that makes the tech industry so exciting.

== Notes to committee/motivation
Looking at ways that different career paths can lead to diverse ideas and thoughts and how those can impact innovation in technology. Encouraging and welcoming all backgrounds can help that continue and improve the industry.