= Be a Kid Again: Learn the latest Java features through exploration

== Alternate titles

== Tags
* java
* programming
* data
* analysis

== Elevator pitch (300 characters or less)
Learning to use the changes in the latest release of Java might seem like a daunting task, but we will see how putting the version diffs in a graph database helped the presenter tackle the new features in a fun and exploratory way. Live coding will show you how to apply what’s new to your code!

== Short abstract
Learning how to apply the changes in the latest release of Java might seem like a daunting task, but we’ll see how to hack our own hesitation and make it fun. By putting the version diffs in a graph database, the presenter tapped into natural curiosity and helped her tackle the new features in a fun and exploratory way.

Live demos will bring the code to life as we explore the changes in the language and see how to actually apply these in our projects.

== Abstract
Learning how to apply the changes and features in the latest release of Java might seem like a daunting task, but we will see how to hack our own hesitation and make it fun. By putting the version diffs of Java in a graph database, the presenter tapped into natural curiosity, helping her tackle the new features in a fun and exploratory way.

We will use the graph as a tool to understand levels of changes and things we might need to upgrade in existing code or new features we might want to take advantage of. We can use the graph as a reference as we navigate code projects where we will put the Java language improvements to the test.

== Notes to committee/motivation
Up-skilling to learn new technology or language changes all the time can be exhausting, but by tackling them in a new and creative way, we can increase our motivation. I want to share how I made that process for Java 17 fun and then what the new updates actually work.

== Speaker bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver. She holds a Master’s degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value. She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis! Her passion is finding ways to organize chaos and deliver software more effectively.