= Agents, Tools, and MCP, oh my! Next-level AI concepts for developers

== Alternate titles
* Next-level AI: Upgrade your skills with agents, MCP, and more

== Tags
* genai
* llm
* agent
* mcp
* rag

== Abstract
AI is evolving fast, and so are the ways developers can integrate it into tech systems. A flurry of new approaches and tools surfaces every week, and it's hard to know where to focus.

In this session, we will pull back the curtain on the next wave of AI development with agents, tool integrations, and Model Context Protocol (MCP). We will break down what AI agents are, how they interact with tools and APIs, and why context is critical for building smarter, more reliable applications. Next, we will look at MCP and how it standardizes communication between AI models and external systems.

Along the way, we will touch on related concepts and step through code and demos, giving you a complete roadmap to level up your AI skills. You won't need a yellow brick road to follow along, but you will discover some magical new tricks to level up your AI skills!

== Notes to committee/motivation
The information to keep up with in this field continues to accelerate, and it is difficult to understand how new technologies fit into the picture. This session will cut through the hype and overview some newer trends, focusing on understanding what they are, how they work, and when (or when not) to use them.