# session-abstracts
= Abstracts for topics in my current repertoire

== Maintainer
* Jennifer Reif

== Purpose
In this repository are a list of session topics I am able to deliver.
Session Formats:
* Conference and meetup sessions for varying lengths (~30-60 minutes)
* Keynote sessions for varying lengths (~30-60 minutes)
* Workshop sessions for varying lengths (~1.5-4 hours)

== Repository session formats
Each session abstract is formatted as an Asciidoc document (.adoc extension), which can be opened in any plain text editor.

== Speaker Information

=== Bio
Jennifer Reif is a Developer Advocate at Neo4j, speaker, and writer who helps developers make better use of their data. An avid developer and problem-solver, she explores databases, data modeling, and emerging technologies like AI through hands-on experiments, sharing what she learns at conferences and digital channels around the world. With a background in CMIS and a knack for untangling complex systems, Jennifer focuses on turning scattered data and complex topics into clear, understandable actions to build better applications.

=== Alternate Bio
Jennifer Reif is a Developer Advocate at Neo4j, speaker, and writer focused on helping developers make sense of their data. She shares hands-on experiments with databases, AI, and developer tools at events and on her website at https://jmhreif.com/[jmhreif.com^].

You can explore her code on GitHub (https://github.com/JMHReif[github.com/JMHReif^]), watch her talks on https://www.youtube.com/playlist?list=PLf8aIqYXdUo9Su_yALHM2Z4CPDnl491wt[YouTube^], or follow along on X/Twitter (https://twitter.com/JMHReif[@JMHReif^]) and LinkedIn (https://www.linkedin.com/in/jmhreif/[jmhreif^]) for the occasional update.

=== Photos
* https://drive.google.com/file/d/1O5dz5mYIWHpjcmFZleyHtWIxMlo0uq51/view?usp=sharing[Click here to view/download headshot^]
* https://drive.google.com/file/d/1i5XaKpkcmTnbtIFpgNXeANkev4N6ATlx/view?usp=sharing[Click here to view/download profile image^]

=== Contact
* Github: https://github.com/JMHReif[JMHReif^]
* X: https://x.com/JMHReif[@JMHReif^]
* LinkedIn: https://www.linkedin.com/in/jmhreif/[jmhreif^]
* Website: https://jmhreif.com/[jmhreif.com^]
* YouTube speaking playlist: https://www.youtube.com/playlist?list=PLf8aIqYXdUo9Su_yALHM2Z4CPDnl491wt[JMHReif^]
