= Databases for All Ages - Exploring Data with a Graph Database

== Alternate titles
* ??

== Tags
* intro
* learning
* data
* graph

== Elevator pitch (300 characters or less)
Traditional data stores make it difficult to explore data without specialized knowledge. This is where graphs can help by making data accessible and valuable for all skill levels and ages. We will explore creating, querying, displaying, and interacting with your graph data.

== Abstract
In this connected world, traditional data stores often make it difficult to get value out of data without specialized knowledge and training on the model, query language, and other practices. Graph databases focus not only on the entities, but the connections between them, so we can see related data quickly and easily. This makes analyzing and pulling value from a data set incredibly simple.

In this session, we will explore graphs and how they provide value in the way they store data. We will see how to transform our own projects into graphs, organize the data for querying, and access the data for exploration through queries, visualization, and applications. Join us to learn how graph databases are used to improve the data world and help everyone easily make sense of connected data!

== Notes to committee/motivation
Technology (especially databases) can feel overly complex and un-user-friendly. This session explores ways that graph databases help overcome that through their typical approaches - flexible data model, more concrete query language, point-and-click data visualization tools, and more. I've seen people use graphs to teach students, introduce data to kids, and more. This session aims to showcase those strengths.