= Banishing Import Dread: Taking the Pain out of Data Ingestion

== Alternate Titles
* Conquering Data Import like a Boss

== Abstract
In today’s rapidly evolving and expanding platforms, there are many standards and recommended practices for IT systems and processes. But there is one capability that isn’t yet universal: data import.

Moving and translating data isn’t just a one-and-done task, either. It’s a continuous cycle of updates to core and subsystem stores, feeding data generated, manipulated, & gathered in various places to and from so-called “systems of truth”.

Whether dealing with new data, migrating data, or translating/integrating data, we often must write code to move this priceless and temperamental asset across systems and structures. Even the initial move can consume a staggering amount of time and resources. Adding incremental updates, changing business requirements, and system upgrades to the mix only increases the pain and risk. How can we reduce both? Do better tools exist to streamline and simplify these continuous/repeated processes?

In this session, we will evaluate & demonstrate ways to transport & transform different types of data into three main categories of databases: relational, nosql, & graph. From extra tools and helpful hints to out-of-the-box solutions, come and learn how to streamline your project’s critical path and focus more on business needs by simplifying your data import process!

== Notes to committee/motivation
No matter the databases involved, the toughest challenge in many projects is getting existing data transported reliably from one system or format to another and maintaining its integrity and “freshness”. In this session, I explore the various ways & tools available to do so and show the pros & cons of each in various scenarios.

== Speaker Bio
Jennifer Reif is a Developer Relations Engineer at Neo4j, conference speaker, blogger, and an avid developer and problem-solver.
She holds a Master’s degree in Computer Management and Information Systems and has worked with large enterprises to organize and make sense of widespread data assets and leverage them for maximum business value.
She has worked with a variety of commercial and open source tools and enjoys learning new technologies, sometimes on a daily basis!
Her passion is finding ways to organize chaos and deliver software more effectively.